#!/usr/bin/env node

var program = require('commander');
var child_process = require('child_process');
var version = require('./package.json').version;

function copyDir(src, dist) {
  try {
    child_process.spawn('cp', ['-r', src, dist]);
  } catch (e) {
    console.log(e);
  }
}

program
  .usage('[command] <options ...>')
  .version(version)
  .option('-n, --name', '项目名称')
  .option('-s, --super', '定制化')
  .option('-p, --path', '项目路径')
  .option('-v, --version', 'monster-ball version')

program
  .command('new <projectName>')
  .description('create new project')
  .action(function(data) {
    console.log('cwd', process.cwd());
    console.log('__dirname', __dirname);
    console.log('__process.execPath', process.execPath);
    copyDir(__dirname + '/vue', process.cwd() + '/' + data)
    console.log('create new project', data);
  })

program
  .command('test <projectPath>')
  .description('test a project')
  .action(function(data) {
    console.log('test a project');
  })

program.parse(process.argv);


if (program.super) {
  console.log('program.super');
}

if (program.path) {
  console.log('program.path');
}

if (program.joy) {
  console.log('program.joy');
}

// if (program.version) {
//   console.log('monster-ball version:',version);
// }
