#!/usr/bin/env node

var program = require('commander');
var child_process = require('child_process');

function copyDir(src, dist) {
  child_process.spawn('cp', ['-r', src, dist]);
}

program
  .usage('[command] <options ...>')
  .version(require('./package.json').version)
  .option('-n, --name', '项目名称')
  .option('-s, --super', '定制化')
  .option('-p, --path', '项目路径')

program
  .command('new <projectName>')
  .description('create new project')
  .action(function(data) {
    copyDir('./vue',__dirname + data)
    console.log('create new project',data);
  })

program
  .command('test <projectPath>')
  .description('test a project')
  .action(function(data) {
    console.log('test a project');
  })

program.parse(process.argv);


if (program.super) {
  console.log('program.super');
}

if (program.path) {
  console.log('program.path');
}

if (program.joy){
  console.log('program.joy');
}

if (program.name) {
  // console.log('program.name');
}
